from pydantic import BaseModel
from typing import List, Annotated

class UserDemographics(BaseModel):
    age: Annotated[int, "Age of the user"]
    gender: Annotated[str, "Gender of the user"]
    location: Annotated[str, "Location of the user"]
    education_level: Annotated[str, "Education level of the user"]
    job_title: Annotated[str, "Job title of the user"]

class QARequestModel(BaseModel):
    question: Annotated[str, "The legal question asked by the user"]
    demographics: Annotated[UserDemographics, "Demographic information of the user asking the question"]
    

class ActionPlanModel(BaseModel):
    title: Annotated[str, "Title of the action plan item"]
    description: Annotated[str, "Detailed description of the action plan item"]

class QAResponseModel(BaseModel):
    answer: Annotated[str, "The answer generated by the QA system"]
    confidence: Annotated[float, "Confidence score of the answer between 0 and 1"]
    legal_references: Annotated[List[str], "List of legal document references used to generate the answer"]
    action_plan: Annotated[List[ActionPlanModel], "List of action plan items suggested based on the answer"]
    