from typing import Annotated, List, Literal, Optional

from pydantic import BaseModel, Field

class UserDemographics(BaseModel):
    age: Annotated[int, Field(description="Age of the user")]
    gender: Annotated[str, Field(description="Gender of the user")]
    location: Annotated[str, Field(description="Location of the user")]
    education_level: Annotated[str, Field(description="Education level of the user")]
    job_title: Annotated[str, Field(description="Job title of the user")]

class QARequestModel(BaseModel):
    question: Annotated[str, Field(description="The legal question asked by the user")]
    demographics: Annotated[UserDemographics, Field(description="Demographic information of the user asking the question")]
    preferred_language: Annotated[
        Literal["en", "hi"],
        Field(description="Preferred answer language, English(en) or Hindi(hi)"),
    ] = "en"

class ActionPlanModel(BaseModel):
    title: Annotated[str, Field(description="Title of the action plan item")]
    description: Annotated[str, Field(description="Detailed description of the action plan item")]


class SourcePassageModel(BaseModel):
    source: Annotated[str, Field(description="Source document name")]
    quote: Annotated[str, Field(description="Relevant quote from retrieved context")]
    section: Annotated[
        Optional[str], Field(description="Section/chapter metadata if available")
    ] = None
    relevance_score: Annotated[
        float, Field(description="Normalized relevance score between 0 and 1")
    ]

class QAResponseModel(BaseModel):
    answer: Annotated[str, Field(description="The answer generated by the QA system")]
    confidence: Annotated[float, Field(description="Confidence score of the answer between 0 and 1")]
    legal_references: Annotated[
        List[str],
        Field(
            default_factory=list,
            description="List of legal document references used to generate the answer",
        ),
    ]
    action_plan: Annotated[
        List[ActionPlanModel],
        Field(
            default_factory=list,
            description="List of action plan items suggested based on the answer",
        ),
    ]
    source_passages: Annotated[
        List[SourcePassageModel],
        Field(
            default_factory=list,
            description="Quote-level supporting passages from retrieved documents",
        ),
    ]
    