export const educationLevels = [
  { value: "no_formal_education", label: "No Formal Education" },
  { value: "primary_school", label: "Primary School" },
  { value: "middle_school", label: "Middle School" },
  { value: "high_school", label: "High School" },
  { value: "higher_secondary", label: "Higher Secondary" },
  { value: "diploma", label: "Diploma" },
  { value: "graduate", label: "Graduate (Bachelor's)" },
  { value: "postgraduate", label: "Postgraduate (Master's)" },
  { value: "doctorate", label: "Doctorate (PhD)" },
];

export const occupations = [
  "Daily Wage Worker",
  "Farmer",
  "Factory Worker",
  "Construction Worker",
  "Domestic Worker",
  "Driver",
  "Street Vendor",
  "Shop Owner",
  "Salaried Employee",
  "Self-Employed Professional",
  "Business Owner",
  "Teacher",
  "Healthcare Worker",
  "Government Employee",
  "Student",
  "Unemployed",
  "Retired",
  "Other",
];

export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];
